spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: Tushartxt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE